/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/obelix/cvs/Optix_Tracer/sources/LexParser/FlexZemax.cc,v 1.1 2010-08-11 11:38:01 itomauch Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
class istream;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24
static yyconst short int yy_accept[219] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   24,   22,   22,   22,
        3,   22,   22,   22,   22,   22,   22,   10,   22,   22,
        9,   10,   10,   10,   22,   22,   11,   22,   22,   22,
       13,   22,   22,   16,   22,   22,   22,   22,   17,   22,
       22,   18,   22,   22,    8,   19,   22,   22,   21,    0,
        0,    3,    0,    0,    0,    0,    0,    0,   10,    0,
        9,    9,   10,    9,   10,   10,   10,    0,   11,   11,
        0,    0,   13,   13,    0,   16,   16,    0,    0,    0,

       17,   17,    0,   18,   18,    0,    8,    8,    0,   21,
        0,    0,    4,    3,    0,    0,    0,    0,    9,   10,
       10,   10,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    9,   10,
       10,   10,   10,    0,   11,    0,    0,   13,    0,   16,
        0,    0,    0,   17,    0,   18,    0,    8,    0,    0,
        0,    0,    0,    0,   10,    9,   10,   10,    0,    0,
       15,    0,    0,    0,    0,    0,    0,   10,   10,    0,
        0,    0,    0,    0,    0,    0,    0,   10,   10,    0,
        0,    0,    0,    0,    6,    7,    5,    9,   12,   14,

       20,    0,    0,    0,    0,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    4,    1,    1,    1,    1,
        1,    1,    5,    1,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,   10,    9,    9,   11,    1,    1,
        1,    1,    1,    1,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   19,
       19,   27,   28,   29,   30,   19,   19,   19,   31,   19,
        1,    1,    1,    1,    8,    1,   32,   19,   33,   19,

       34,   35,   19,   19,   36,   19,   19,   19,   19,   37,
       19,   19,   19,   38,   39,   40,   41,   19,   19,   19,
       42,   19,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    1,    1,    2,    1,    2,    2,    2,    2,    2,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2
    } ;

static yyconst short int yy_base[222] =
    {   0,
        0,    1,    7,   11,   26,   28,   56,   84,  107,  130,
       92,  115,  153,  176,  138,  161,  184,  196,  204,  211,
       24,   46,   22,   32,  100,  146,  471,  472,  454,  439,
        0,  444,  454,   41,  440,  447,   43,    0,    4,    9,
       68,  427,  447,  432,   73,   87,  122,  424,  170,  109,
      188,  216,  124,  221,  423,  453,  226,  132,  231,  235,
      155,  239,  243,  178,  247,  472,   70,  199,  206,  433,
      430,  249,  444,  434,  428,  427,  425,  439,    0,  251,
      255,  257,  259,  265,  415,  424,  421,  261,  269,  271,
      412,  273,  279,  283,  275,  287,  291,  411,  432,  293,

      299,  302,  304,  312,  314,  306,  319,  322,  406,  324,
      415,  425,  472,  472,  414,  428,  414,  334,  336,  402,
      409,  419,  344,  399,  352,  354,  398,  411,  362,  368,
      370,  397,  428,  418,  414,  399,  412,  332,  356,  376,
      389,  422,  412,  374,  378,  386,  380,  382,  384,  386,
      385,  411,  388,  390,  392,  394,  396,  398,  388,  394,
      404,  404,  349,  343,  400,  402,  315,  333,  301,  299,
      472,  294,  294,  294,  277,  273,  268,  250,  261,  223,
      215,  217,  218,  240,  215,  211,  207,  158,  189,  133,
      130,  118,  138,  134,  472,  472,  472,    0,  472,  472,

      472,  118,  114,   97,   74,  472,   76,   78,   40,   23,
       22,   20,   26,    9,    1,    1,  472,  472,  412,  414,
        0
    } ;

static yyconst short int yy_def[222] =
    {   0,
      219,  219,  219,  219,  219,  219,  220,  220,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  221,  218,  218,
      221,  221,  221,  221,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  221,  218,
      218,  218,  221,  221,  221,  221,  221,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  221,  221,
      221,  221,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  221,
      221,  221,  221,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  221,  221,  221,  221,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  221,  221,  218,
      218,  218,  218,  218,  218,  218,  218,  221,  221,  218,
      218,  218,  218,  218,  218,  218,  218,  221,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,    0,  218,  218,
      218
    } ;

static yyconst short int yy_nxt[515] =
    {   0,
      218,   79,  218,  218,  218,  218,  218,  218,   72,   72,
       80,  217,   81,   81,  218,   31,   31,   82,   82,   31,
       31,  218,   29,   29,  218,   66,   32,   30,   30,   29,
       32,  216,   33,   29,   34,  215,   33,  214,   34,   35,
       36,   35,   36,  213,   29,  212,   29,   66,   29,   67,
       29,   30,  211,   37,   29,   37,   28,   28,   28,   67,
       28,   39,   40,   28,   41,   41,   28,  210,   29,   75,
       71,   78,   71,   30,   83,   42,   84,   84,   43,   88,
      209,   89,   89,   44,   28,   28,   28,  208,   28,   39,
       40,   28,   41,   41,   28,   90,   90,   49,   50,   71,

       51,   51,  207,   42,   68,   68,   43,  206,   69,   69,
      109,   44,   45,   46,   29,   47,   47,   94,   94,   30,
       49,   50,   29,   51,   51,  205,   48,   30,   88,   29,
       89,   89,   97,   97,   30,   45,   46,   29,   47,   47,
      102,  102,   30,   57,   58,  204,   59,   59,  203,   48,
       68,   68,   29,  202,   69,   69,  201,   30,   52,   53,
       29,   54,   54,  105,  105,   30,   57,   58,   29,   59,
       59,  200,   55,   30,  199,   29,   92,   56,   93,   93,
       30,   52,   53,   29,   54,   54,  108,  108,   30,   60,
       61,  194,   62,   62,   92,   55,   93,   93,   29,  198,

       56,   60,   61,   30,   62,   62,   29,  110,  110,   63,
       64,   30,   65,   65,  110,  110,   63,   64,   29,   65,
       65,  197,   95,   30,   96,   96,   29,   95,  196,   96,
       96,   30,  100,   29,  101,  101,  195,  100,   30,  101,
      101,  103,  194,  104,  104,  103,  193,  104,  104,  106,
      192,  107,  107,  106,  191,  107,  107,   72,   72,   82,
       82,   80,  190,   81,   81,   82,   82,  119,  119,   90,
       90,   83,  118,   84,   84,   88,  189,   89,   89,   90,
       90,   94,   94,   97,   97,   92,  123,   93,   93,  188,
      118,   94,   94,   95,  187,   96,   96,  186,  125,   97,

       97,  102,  102,  185,  123,  100,  126,  101,  101,  184,
      102,  102,  105,  105,  108,  108,  125,  129,  103,  183,
      104,  104,  105,  105,  126,  106,  182,  107,  107,  130,
      108,  108,  110,  110,  181,  129,  180,  131,  138,  138,
      139,  139,  139,  139,  119,  119,  179,  130,  144,  144,
      178,  140,  145,  145,  177,  131,  147,  147,  149,  149,
      148,  148,  150,  150,  139,  139,  153,  153,  176,  140,
      154,  154,  155,  155,  157,  157,  156,  156,  158,  158,
      138,  165,  145,  145,  166,  166,  145,  145,  148,  148,
      148,  148,  150,  150,  150,  150,  154,  154,  154,  154,

      156,  156,  156,  156,  158,  158,  158,  158,  166,  166,
      166,  166,   28,   28,   38,   38,  175,  174,  173,  172,
      171,  170,  169,  168,  160,  167,  164,  163,  162,  161,
      160,  159,  152,  151,  146,  143,  142,  141,  137,  136,
      135,  134,  133,  132,  128,  127,  124,  122,  121,  120,
      117,  116,  115,  114,  114,  113,  112,  111,   99,   98,
       91,   87,   86,   85,   77,   76,   74,   73,   71,   70,
      218,   27,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218
    } ;

static yyconst short int yy_chk[515] =
    {   0,
        0,  221,    0,    0,    0,    0,    0,    0,   31,   31,
       39,  216,   39,   39,    0,    3,    3,   40,   40,    4,
        4,    0,    1,    2,    0,   21,    3,    1,    2,    3,
        4,  215,    3,    4,    3,  214,    4,  213,    4,    5,
        5,    6,    6,  212,   23,  211,   21,   22,    5,   23,
        6,   21,  210,    5,   24,    6,    7,    7,    7,   24,
        7,    7,    7,    7,    7,    7,    7,  209,   22,   34,
       34,   37,   37,   22,   41,    7,   41,   41,    7,   45,
      208,   45,   45,    7,    8,    8,    8,  207,    8,    8,
        8,    8,    8,    8,    8,   46,   46,   11,   11,   67,

       11,   11,  205,    8,   25,   25,    8,  204,   25,   25,
       67,    8,    9,    9,   11,    9,    9,   50,   50,   11,
       12,   12,   25,   12,   12,  203,    9,   25,   47,    9,
       47,   47,   53,   53,    9,   10,   10,   12,   10,   10,
       58,   58,   12,   15,   15,  202,   15,   15,  194,   10,
       26,   26,   10,  193,   26,   26,  192,   10,   13,   13,
       15,   13,   13,   61,   61,   15,   16,   16,   26,   16,
       16,  191,   13,   26,  190,   13,   49,   13,   49,   49,
       13,   14,   14,   16,   14,   14,   64,   64,   16,   17,
       17,  189,   17,   17,   51,   14,   51,   51,   14,  188,

       14,   18,   18,   14,   18,   18,   17,   68,   68,   19,
       19,   17,   19,   19,   69,   69,   20,   20,   18,   20,
       20,  187,   52,   18,   52,   52,   19,   54,  186,   54,
       54,   19,   57,   20,   57,   57,  185,   59,   20,   59,
       59,   60,  184,   60,   60,   62,  183,   62,   62,   63,
      182,   63,   63,   65,  181,   65,   65,   72,   72,   80,
       80,   81,  180,   81,   81,   82,   82,   83,   83,   88,
       88,   84,   82,   84,   84,   89,  179,   89,   89,   90,
       90,   92,   92,   95,   95,   93,   90,   93,   93,  178,
       82,   94,   94,   96,  177,   96,   96,  176,   94,   97,

       97,  100,  100,  175,   90,  101,   97,  101,  101,  174,
      102,  102,  103,  103,  106,  106,   94,  102,  104,  173,
      104,  104,  105,  105,   97,  107,  172,  107,  107,  105,
      108,  108,  110,  110,  170,  102,  169,  108,  118,  118,
      138,  138,  118,  118,  119,  119,  168,  105,  123,  123,
      167,  119,  123,  123,  164,  108,  125,  125,  126,  126,
      125,  125,  126,  126,  139,  139,  129,  129,  163,  119,
      129,  129,  130,  130,  131,  131,  130,  130,  131,  131,
      140,  140,  144,  144,  140,  140,  145,  145,  147,  147,
      148,  148,  149,  149,  150,  150,  153,  153,  154,  154,

      155,  155,  156,  156,  157,  157,  158,  158,  165,  165,
      166,  166,  219,  219,  220,  220,  162,  161,  160,  159,
      152,  151,  146,  143,  142,  141,  137,  136,  135,  134,
      133,  132,  128,  127,  124,  122,  121,  120,  117,  116,
      115,  112,  111,  109,   99,   98,   91,   87,   86,   85,
       78,   77,   76,   75,   74,   73,   71,   70,   56,   55,
       48,   44,   43,   42,   36,   35,   33,   32,   30,   29,
       27,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "./sources/LexParser/LexZemax.l"
#define INITIAL 0
#line 3 "./sources/LexParser/LexZemax.l"
  // Übersetzt wird das ganze mit flex++ xml.lex und dann linken mit -lfl
  // flex++ xml.lex; g++ lex.yy.cc -lfl; ./a.out < beispiel.xml
  // flex++ ito.lex; g++ lex.yy.cc -lfl; . do.sh > test

  // Vorgehen:
  // 1. Das automatische Anlegen der Objekte für den Bereicht OBJECT hinkriegen
  // 2. Den ganzen Kram mehr oder weniger kopieren und für MeasurementEntity machen
  // 3. Den Kram in unsere Task Klasse einbauen / dazulinken / Makefile
  // 4. Dokumentation
  // 5. Die ganzen set/get Funktionen für Task machen, so dass bequemes Interface
  //    vorhanden ist.
  // 6. Definition der ganzen Variablen, die für uns relevant sind
  // 7. Output 
  // 8. Tests für Mikrolinsen und ein paar andere Objekte
  // Fehlerdetektion in den Input Files !

#include<stdio.h>

char yylval[20];

extern FILE *yyin;

extern FILE *yyout;

char testchar[20];
double testdouble;


#define SURFSUM 1

#define SURFSUM_TYPE 2

#define SURFSUM_CMT 3

#define SURFSUM_RAD 4

#define SURFSUM_TKS 5

#define SURFSUM_GLS 6

#define SURFSUM_DIA 7

#define SURFSUM_CON 8

#define SURFSUM_CRDBRK 9

#define SURFSUM_END 10

#define LENSNOTES 11

#define LENSNOTES_SURF 12

#line 565 "lex.yy.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 70 "./sources/LexParser/LexZemax.l"

#line 694 "lex.yy.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 472 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 71 "./sources/LexParser/LexZemax.l"
{
           BEGIN SURFSUM;
          }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 75 "./sources/LexParser/LexZemax.l"
{
		   BEGIN LENSNOTES;
		  }          
	YY_BREAK
/* ---------------------------------------------------------------*/
case 3:
YY_RULE_SETUP
#line 81 "./sources/LexParser/LexZemax.l"
{
			fprintf( yyout, "surf nr: %s;", yytext); 
			BEGIN SURFSUM_TYPE;
 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "./sources/LexParser/LexZemax.l"
{
			fprintf( yyout, "last surf\n"); 
			BEGIN 0;
 }
	YY_BREAK
/*------------------------------------------------------------------------*/
case 5:
YY_RULE_SETUP
#line 93 "./sources/LexParser/LexZemax.l"
{
			 fprintf( yyout, "type: standard;");
			 BEGIN SURFSUM_CMT;
 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "./sources/LexParser/LexZemax.l"
{
			 fprintf( yyout, "type: coordinate break;");
			 BEGIN SURFSUM_CRDBRK;
 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "./sources/LexParser/LexZemax.l"
{
			 fprintf( yyout, "type: grating;");
			 BEGIN SURFSUM_CMT;
 }
	YY_BREAK
/*------------------------------------------------------------------------*/
case 8:
YY_RULE_SETUP
#line 111 "./sources/LexParser/LexZemax.l"
{
			 fprintf( yyout, " thickness: %s", yytext);
			 BEGIN SURFSUM_END;
 }
	YY_BREAK
/*------------------------------------------------------------------------*/
case 9:
YY_RULE_SETUP
#line 118 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " no name; radius %s;", yytext);
			 BEGIN SURFSUM_TKS; /* if we don't find a valid name, assign no name and interprete current text as radius. Therefore proceed to thickness */
 }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 123 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " name: %s;", yytext);
			 BEGIN SURFSUM_RAD;
 } 
	YY_BREAK
/*--------------------------------------------------------------------------*/
case 11:
YY_RULE_SETUP
#line 130 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " rad: %s;", yytext);
			 BEGIN SURFSUM_TKS;
 } 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 135 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " rad: %s;", yytext);
			 BEGIN SURFSUM_TKS;
 } 
	YY_BREAK
/*--------------------------------------------------------------------------*/
case 13:
YY_RULE_SETUP
#line 142 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " thickness: %s;", yytext);
			 BEGIN SURFSUM_GLS; 
 }
	YY_BREAK
/*---------------------------------------------------------------------------*/
case 14:
YY_RULE_SETUP
#line 149 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " glass: %s;", yytext);
			 BEGIN SURFSUM_DIA; 
 } 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 154 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " glass: %s;", yytext);
			 BEGIN SURFSUM_DIA; 
 } 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 159 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " no glass; diameter: %s;", yytext);
			 BEGIN SURFSUM_CON; /* if we find a number here, we probably don't have any glass and read the diameter instead. So proceed to conic directly */ 
 } 
	YY_BREAK
/*-------------------------------------------------------------------------------*/
case 17:
YY_RULE_SETUP
#line 166 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " diameter: %s;", yytext);
			 BEGIN SURFSUM_CON; 
 }
	YY_BREAK
/*---------------------------------------------------------------------------------*/
case 18:
YY_RULE_SETUP
#line 173 "./sources/LexParser/LexZemax.l"
{
 			 fprintf( yyout, " con: %s", yytext);
			 BEGIN SURFSUM_END; 
 }
	YY_BREAK
/*------------------------------------------------------------------------*/
case 19:
YY_RULE_SETUP
#line 180 "./sources/LexParser/LexZemax.l"
{
			fprintf( yyout, "\n");
			BEGIN SURFSUM;
 }	
	YY_BREAK
/*-------------------------------------------------------------------------*/
/*                                                                         */
/*					Lense notes											 */
/*																		 */
/*-------------------------------------------------------------------------*/
case 20:
YY_RULE_SETUP
#line 191 "./sources/LexParser/LexZemax.l"
{
			BEGIN LENSNOTES_SURF;
  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 196 "./sources/LexParser/LexZemax.l"
{
			sprintf(testchar, "%s", yytext);
			testdouble=atof(testchar);
			fprintf( yyout, "%f \n", testdouble);
			BEGIN 0;
  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 203 "./sources/LexParser/LexZemax.l"
{}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 204 "./sources/LexParser/LexZemax.l"
ECHO;
	YY_BREAK
#line 969 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SURFSUM):
case YY_STATE_EOF(SURFSUM_TYPE):
case YY_STATE_EOF(SURFSUM_CMT):
case YY_STATE_EOF(SURFSUM_RAD):
case YY_STATE_EOF(SURFSUM_TKS):
case YY_STATE_EOF(SURFSUM_GLS):
case YY_STATE_EOF(SURFSUM_DIA):
case YY_STATE_EOF(SURFSUM_CON):
case YY_STATE_EOF(SURFSUM_CRDBRK):
case YY_STATE_EOF(SURFSUM_END):
case YY_STATE_EOF(LENSNOTES):
case YY_STATE_EOF(LENSNOTES_SURF):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 218);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 204 "./sources/LexParser/LexZemax.l"


// ____________________________________________________________

int main()
    {
		yyout = fopen( "e:\\mauch\\prescriptionLexOut.txt", "w" ) ;
		yyin = fopen( "e:\\mauch\\prescription.txt", "r" ) ;
    
		while(yylex() != 0)
			;
		fclose(yyout);
    }