/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
static yyconst short int yy_accept[381] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   38,   36,   36,   36,
       36,   36,   36,    6,   36,   36,    5,   36,   36,   36,
       36,   36,   36,   36,    8,   23,   36,   36,   22,   36,
       36,   10,   36,   36,   12,   36,   36,   14,   36,   36,
       16,   36,   36,   18,   36,   36,   20,   36,   36,   25,
       36,   36,   36,   27,   27,   27,   27,   28,   36,   36,

       30,   36,   36,   31,   36,   36,   33,   36,   36,   35,
        4,    1,    0,    0,    0,    0,    5,    5,    5,    0,
        0,    0,    0,    0,    0,    0,    8,    8,    8,    0,
        0,   22,   22,   22,    0,    0,   10,   10,   10,    0,
        0,   12,   12,   12,    0,    0,   14,   14,   14,    0,
        0,   16,   16,   16,    0,    0,   18,   18,   18,    0,
        0,   20,   20,   20,    0,    0,   25,   25,   25,    0,
        0,    0,    0,   27,    1,   27,   27,   28,    0,   30,
       30,   30,    0,    0,   31,   31,   31,    0,    0,   33,
       33,   33,    0,    0,   35,   35,   35,    0,    3,    0,

       26,    0,    0,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    8,    0,    0,   22,    0,    0,   10,    0,
        0,   12,    0,    0,   14,    0,    0,   16,    0,    0,
       18,    0,    0,   20,    0,    0,   25,   32,   29,   34,
        3,   27,    0,    0,   30,    0,    0,   31,    0,    0,
       33,    0,    0,   35,    0,    0,    5,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    8,    0,   22,    0,
       10,    0,   12,    0,   14,    0,   16,    0,   18,    0,
       20,    0,   25,   27,    0,   30,    0,   31,    0,   33,
        0,   35,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   27,    0,    0,    0,    0,    0,   13,   15,   17,
       19,   27,    0,    0,    0,   21,    0,   27,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   24,    0,    0,
        0,    0,    0,   11,    0,    0,    0,    0,    0,    0,
        0,    7,    0,    0,    0,    0,    0,    0,    9,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    4,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    8,    9,   10,   11,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   23,   24,   25,   26,   27,   28,
       23,   29,   30,   31,   32,   33,   34,   23,   23,   23,
        1,    1,    1,    1,    9,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   23,   24,   25,   26,
       27,   28,   23,   29,   30,   31,   32,   33,   34,   23,
       23,   23,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[35] =
    {   0,
        1,    1,    1,    2,    1,    1,    2,    2,    2,    2,
        2,    2,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static yyconst short int yy_base[383] =
    {   0,
        0,    2,    7,   18,   20,   31,   50,    0,   63,    0,
       91,    0,  102,    0,  109,  116,  123,  130,  137,  144,
      151,  158,  165,  172,  179,  186,  193,  200,  205,  229,
      260,    0,  289,  296,  303,  310,  317,  324,  331,  338,
      345,  352,   33,   56,   61,   74,  772, 1196,  766,  750,
      738,  734,  737, 1196,    1,   20,  206,   32,  726,  732,
      711,  711,  220,   95,  230, 1196,  244,  356,  361,  366,
      370,  375,  380,  384,  389,  394,  398,  403,  408,  412,
      417,  422,  426,  431,  436,  440,  445,  450,  454,  459,
       26,  720,  719,    0,  718,  706,  697,   74,  464,  468,

      473,  478,  482,  487,  492,  496,  501,  506,  510,  515,
     1196, 1196,  699,  700,  710,  223,  520,  524,  529,  538,
      689,  693,  680,  679,   35,  247,  543,  546,  555,  564,
      567,  572,  575,  584,  593,  596,  601,  604,  613,  622,
      625,  630,  633,  642,  651,  654,  659,  662,  671,  680,
      683,  688,  691,  700,  709,  712,  717,  720,  729,  738,
      741,  746,  749,  758,  767,  770,  775,  778,  787,  796,
      694,  685,  682,    0,    0,  666,  665,  799,  802,  807,
      810,  819,  828,  831,  836,  839,  848,  857,  860,  865,
      868,  877,  886,  889,  894,  897,  906,  915, 1196,  647,

     1196,  922,  925,  928,  657,  644,  653,  644,   35,   64,
      935,  938,  941,  948,  951,  954,  961,  964,  967,  974,
      977,  980,  987,  990,  993, 1000, 1003, 1006, 1013, 1016,
     1019, 1026, 1029, 1032, 1039, 1042, 1045, 1196, 1196, 1196,
        0,  625, 1052, 1055, 1058, 1065, 1068, 1071, 1078, 1081,
     1084, 1091, 1094, 1097,  633, 1100, 1103,  621,  627,  630,
      628,  628,  620,  616,  616, 1106, 1109, 1112, 1115, 1118,
     1121, 1124, 1127, 1130, 1133, 1136, 1139, 1142, 1145, 1148,
     1151, 1154, 1157,  599, 1160, 1163, 1166, 1169, 1172, 1175,
     1178, 1181,  594,  604,  591,  596,  572,  585,  584,  579,

      578,  563,  568,  565,  552,  556,  565, 1196, 1196, 1196,
     1196,  543,  559,  529,  556, 1196,  525,  543,  526,  515,
       79,  510,  510,  483,  469,  479,  437,  428,  414,  185,
      412,  409,  368,  362,  356, 1196,  338,  323,  328,  307,
      304,  312,  300,  294,  288,  272,  222,  226,  229,  213,
      229,  221,  198,  213,  207,  194,  185, 1196,  178,  175,
      175,  159,  143, 1196,  140,  139,  127,  116,  136,  119,
       98, 1196,   89,   94,   70,   39,   25,    1, 1196, 1196,
     1193,    0
    } ;

static yyconst short int yy_def[383] =
    {   0,
      381,  381,  381,  381,  381,  381,  381,    7,  381,    9,
        7,   11,   11,   13,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,  381,  381,
      380,   31,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,  381,  381,  381,  381,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  382,  382,  382,  382,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  382,  382,  382,  382,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      382,  382,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  382,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  382,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  382,  380,  380,  380,  380,  380,  382,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,    0,
      380,  380
    } ;

static yyconst short int yy_nxt[1231] =
    {   0,
      380,  174,  380,  380,  380,  380,  380,   49,  116,   49,
      117,  117,  117,  379,   49,   50,   51,   50,   51,   52,
      380,   52,   50,   51,  111,   49,   52,   49,  380,  118,
      118,  118,   53,   50,   51,   50,   51,   52,   49,   52,
       49,  112,  171,   53,  262,  263,   50,   51,   50,   51,
       52,   54,   52,  121,  378,   55,   55,   56,  113,   57,
       57,   57,  209,   49,  210,   50,   51,  377,   49,   52,
       49,   50,   51,  264,  265,   52,   50,   51,   50,   58,
       52,   49,   59,  178,  178,  178,   60,  376,   61,   50,
       51,   62,   48,   52,  325,  323,   63,   63,   64,  111,

       65,   65,   65,   66,  128,  128,  128,   67,   67,   68,
      375,   69,   69,   69,   70,   70,   71,  374,   72,   72,
       72,   70,   70,   71,  373,   72,   72,   72,   73,   73,
       74,  372,   75,   75,   75,   73,   73,   74,  371,   75,
       75,   75,   76,   76,   77,  370,   78,   78,   78,   76,
       76,   77,  369,   78,   78,   78,   79,   79,   80,  368,
       81,   81,   81,   79,   79,   80,  367,   81,   81,   81,
       82,   82,   83,  366,   84,   84,   84,   82,   82,   83,
      365,   84,   84,   84,   85,   85,   86,  364,   87,   87,
       87,   85,   85,   86,  363,   87,   87,   87,   88,   88,

       89,  334,   90,   90,   90,   88,   88,   89,  362,   90,
       90,   90,   49,  119,  361,  117,  117,  117,  335,  360,
       91,   51,  359,  120,   52,  358,  357,  126,   92,  127,
      127,  127,  118,  118,  118,   93,   49,  129,  356,  127,
      127,  127,  355,  354,   91,   51,  353,  130,   52,  352,
      351,  131,   92,  132,  132,  132,  128,  128,  128,   93,
       48,   48,   48,   94,   48,   48,   48,   49,   48,   94,
       94,   94,   48,   94,   94,   95,   96,   94,   94,   97,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   48,   48,   49,  350,   98,   98,

       98,   48,   48,   49,  349,   98,   98,   98,   99,   99,
      100,  348,  101,  101,  101,   99,   99,  100,  347,  101,
      101,  101,  102,  102,  103,  346,  104,  104,  104,  102,
      102,  103,  345,  104,  104,  104,  105,  105,  106,  344,
      107,  107,  107,  105,  105,  106,  343,  107,  107,  107,
      108,  108,  109,  342,  110,  110,  110,  108,  108,  109,
      111,  110,  110,  110,  341,  133,  133,  133,  134,  340,
      132,  132,  132,  136,  111,  137,  137,  137,  135,  138,
      138,  138,  139,  339,  137,  137,  137,  141,  111,  142,
      142,  142,  140,  143,  143,  143,  144,  338,  142,  142,

      142,  146,  111,  147,  147,  147,  145,  148,  148,  148,
      149,  337,  147,  147,  147,  151,  111,  152,  152,  152,
      150,  153,  153,  153,  154,  336,  152,  152,  152,  156,
      111,  157,  157,  157,  155,  158,  158,  158,  159,  333,
      157,  157,  157,  161,  111,  162,  162,  162,  160,  163,
      163,  163,  164,  332,  162,  162,  162,  166,  111,  167,
      167,  167,  165,  168,  168,  168,  169,  331,  167,  167,
      167,  179,  111,  180,  180,  180,  170,  181,  181,  181,
      182,  330,  180,  180,  180,  184,  111,  185,  185,  185,
      183,  186,  186,  186,  187,  329,  185,  185,  185,  189,

      111,  190,  190,  190,  188,  191,  191,  191,  192,  328,
      190,  190,  190,  194,  111,  195,  195,  195,  193,  196,
      196,  196,  197,  327,  195,  195,  195,  119,  326,  117,
      117,  117,  198,  118,  118,  118,  324,  120,  118,  118,
      118,  202,  323,  203,  203,  319,  120,  204,  204,  204,
      129,  322,  127,  127,  127,  128,  128,  128,  321,  320,
      130,  319,  318,  211,  128,  128,  128,  317,  316,  212,
      212,  315,  130,  213,  213,  213,  133,  133,  133,  134,
      314,  132,  132,  132,  133,  133,  133,  313,  312,  135,
      311,  310,  214,  133,  133,  133,  309,  308,  215,  215,

      307,  135,  216,  216,  216,  138,  138,  138,  139,  306,
      137,  137,  137,  138,  138,  138,  305,  304,  140,  303,
      302,  217,  138,  138,  138,  301,  300,  218,  218,  299,
      140,  219,  219,  219,  143,  143,  143,  144,  298,  142,
      142,  142,  143,  143,  143,  297,  296,  145,  295,  294,
      220,  143,  143,  143,  293,  284,  221,  221,  261,  145,
      222,  222,  222,  148,  148,  148,  149,  260,  147,  147,
      147,  148,  148,  148,  259,  258,  150,  255,  242,  223,
      148,  148,  148,  241,  240,  224,  224,  239,  150,  225,
      225,  225,  153,  153,  153,  154,  238,  152,  152,  152,

      153,  153,  153,  208,  207,  155,  206,  205,  226,  153,
      153,  153,  201,  200,  227,  227,  199,  155,  228,  228,
      228,  158,  158,  158,  159,  177,  157,  157,  157,  158,
      158,  158,  176,  175,  160,  173,  172,  229,  158,  158,
      158,  125,  124,  230,  230,  123,  160,  231,  231,  231,
      163,  163,  163,  164,  122,  162,  162,  162,  163,  163,
      163,  115,  114,  165,  113,  112,  232,  163,  163,  163,
      111,  380,  233,  233,  380,  165,  234,  234,  234,  168,
      168,  168,  169,  380,  167,  167,  167,  168,  168,  168,
      380,  380,  170,  380,  380,  235,  168,  168,  168,  380,

      380,  236,  236,  380,  170,  237,  237,  237,  178,  178,
      178,  181,  181,  181,  182,  380,  180,  180,  180,  181,
      181,  181,  380,  380,  183,  380,  380,  243,  181,  181,
      181,  380,  380,  244,  244,  380,  183,  245,  245,  245,
      186,  186,  186,  187,  380,  185,  185,  185,  186,  186,
      186,  380,  380,  188,  380,  380,  246,  186,  186,  186,
      380,  380,  247,  247,  380,  188,  248,  248,  248,  191,
      191,  191,  192,  380,  190,  190,  190,  191,  191,  191,
      380,  380,  193,  380,  380,  249,  191,  191,  191,  380,
      380,  250,  250,  380,  193,  251,  251,  251,  196,  196,

      196,  197,  380,  195,  195,  195,  196,  196,  196,  380,
      380,  198,  380,  380,  252,  196,  196,  196,  380,  380,
      253,  253,  380,  198,  254,  254,  254,  256,  256,  380,
      380,  257,  257,  257,  204,  204,  204,  204,  204,  204,
      266,  266,  380,  380,  267,  267,  267,  213,  213,  213,
      213,  213,  213,  268,  268,  380,  380,  269,  269,  269,
      216,  216,  216,  216,  216,  216,  270,  270,  380,  380,
      271,  271,  271,  219,  219,  219,  219,  219,  219,  272,
      272,  380,  380,  273,  273,  273,  222,  222,  222,  222,
      222,  222,  274,  274,  380,  380,  275,  275,  275,  225,

      225,  225,  225,  225,  225,  276,  276,  380,  380,  277,
      277,  277,  228,  228,  228,  228,  228,  228,  278,  278,
      380,  380,  279,  279,  279,  231,  231,  231,  231,  231,
      231,  280,  280,  380,  380,  281,  281,  281,  234,  234,
      234,  234,  234,  234,  282,  282,  380,  380,  283,  283,
      283,  237,  237,  237,  237,  237,  237,  285,  285,  380,
      380,  286,  286,  286,  245,  245,  245,  245,  245,  245,
      287,  287,  380,  380,  288,  288,  288,  248,  248,  248,
      248,  248,  248,  289,  289,  380,  380,  290,  290,  290,
      251,  251,  251,  251,  251,  251,  291,  291,  380,  380,

      292,  292,  292,  254,  254,  254,  254,  254,  254,  257,
      257,  257,  257,  257,  257,  267,  267,  267,  267,  267,
      267,  269,  269,  269,  269,  269,  269,  271,  271,  271,
      271,  271,  271,  273,  273,  273,  273,  273,  273,  275,
      275,  275,  275,  275,  275,  277,  277,  277,  277,  277,
      277,  279,  279,  279,  279,  279,  279,  281,  281,  281,
      281,  281,  281,  283,  283,  283,  283,  283,  283,  286,
      286,  286,  286,  286,  286,  288,  288,  288,  288,  288,
      288,  290,  290,  290,  290,  290,  290,  292,  292,  292,
      292,  292,  292,   48,   48,   47,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380
    } ;

static yyconst short int yy_chk[1231] =
    {   0,
        0,  382,    0,    0,    0,    0,    0,    1,   55,    2,
       55,   55,   55,  378,    3,    1,    1,    2,    2,    1,
        0,    2,    3,    3,   56,    4,    3,    5,    0,   56,
       56,   56,    3,    4,    4,    5,    5,    4,    6,    5,
       43,   91,   91,    4,  209,  209,    6,    6,   43,   43,
        6,    7,   43,   58,  377,    7,    7,    7,   58,    7,
        7,    7,  125,   44,  125,    7,    7,  376,   45,    7,
        9,   44,   44,  210,  210,   44,   45,   45,    9,    9,
       45,   46,    9,   98,   98,   98,    9,  375,    9,   46,
       46,    9,   11,   46,  321,  321,   11,   11,   11,   64,

       11,   11,   11,   13,   64,   64,   64,   13,   13,   13,
      374,   13,   13,   13,   15,   15,   15,  373,   15,   15,
       15,   16,   16,   16,  371,   16,   16,   16,   17,   17,
       17,  370,   17,   17,   17,   18,   18,   18,  369,   18,
       18,   18,   19,   19,   19,  368,   19,   19,   19,   20,
       20,   20,  367,   20,   20,   20,   21,   21,   21,  366,
       21,   21,   21,   22,   22,   22,  365,   22,   22,   22,
       23,   23,   23,  363,   23,   23,   23,   24,   24,   24,
      362,   24,   24,   24,   25,   25,   25,  361,   25,   25,
       25,   26,   26,   26,  360,   26,   26,   26,   27,   27,

       27,  330,   27,   27,   27,   28,   28,   28,  359,   28,
       28,   28,   29,   57,  357,   57,   57,   57,  330,  356,
       29,   29,  355,   57,   29,  354,  353,   63,   29,   63,
       63,   63,  116,  116,  116,   29,   30,   65,  352,   65,
       65,   65,  351,  350,   30,   30,  349,   65,   30,  348,
      347,   67,   30,   67,   67,   67,  126,  126,  126,   30,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   33,   33,  346,   33,   33,

       33,   34,   34,   34,  345,   34,   34,   34,   35,   35,
       35,  344,   35,   35,   35,   36,   36,   36,  343,   36,
       36,   36,   37,   37,   37,  342,   37,   37,   37,   38,
       38,   38,  341,   38,   38,   38,   39,   39,   39,  340,
       39,   39,   39,   40,   40,   40,  339,   40,   40,   40,
       41,   41,   41,  338,   41,   41,   41,   42,   42,   42,
       68,   42,   42,   42,  337,   68,   68,   68,   69,  335,
       69,   69,   69,   70,   71,   70,   70,   70,   69,   71,
       71,   71,   72,  334,   72,   72,   72,   73,   74,   73,
       73,   73,   72,   74,   74,   74,   75,  333,   75,   75,

       75,   76,   77,   76,   76,   76,   75,   77,   77,   77,
       78,  332,   78,   78,   78,   79,   80,   79,   79,   79,
       78,   80,   80,   80,   81,  331,   81,   81,   81,   82,
       83,   82,   82,   82,   81,   83,   83,   83,   84,  329,
       84,   84,   84,   85,   86,   85,   85,   85,   84,   86,
       86,   86,   87,  328,   87,   87,   87,   88,   89,   88,
       88,   88,   87,   89,   89,   89,   90,  327,   90,   90,
       90,   99,  100,   99,   99,   99,   90,  100,  100,  100,
      101,  326,  101,  101,  101,  102,  103,  102,  102,  102,
      101,  103,  103,  103,  104,  325,  104,  104,  104,  105,

      106,  105,  105,  105,  104,  106,  106,  106,  107,  324,
      107,  107,  107,  108,  109,  108,  108,  108,  107,  109,
      109,  109,  110,  323,  110,  110,  110,  117,  322,  117,
      117,  117,  110,  118,  118,  118,  320,  117,  119,  119,
      119,  118,  319,  120,  120,  318,  119,  120,  120,  120,
      127,  317,  127,  127,  127,  128,  128,  128,  315,  314,
      127,  313,  312,  128,  129,  129,  129,  307,  306,  130,
      130,  305,  129,  130,  130,  130,  131,  131,  131,  132,
      304,  132,  132,  132,  133,  133,  133,  303,  302,  132,
      301,  300,  133,  134,  134,  134,  299,  298,  135,  135,

      297,  134,  135,  135,  135,  136,  136,  136,  137,  296,
      137,  137,  137,  138,  138,  138,  295,  294,  137,  293,
      284,  138,  139,  139,  139,  265,  264,  140,  140,  263,
      139,  140,  140,  140,  141,  141,  141,  142,  262,  142,
      142,  142,  143,  143,  143,  261,  260,  142,  259,  258,
      143,  144,  144,  144,  255,  242,  145,  145,  208,  144,
      145,  145,  145,  146,  146,  146,  147,  207,  147,  147,
      147,  148,  148,  148,  206,  205,  147,  200,  177,  148,
      149,  149,  149,  176,  173,  150,  150,  172,  149,  150,
      150,  150,  151,  151,  151,  152,  171,  152,  152,  152,

      153,  153,  153,  124,  123,  152,  122,  121,  153,  154,
      154,  154,  115,  114,  155,  155,  113,  154,  155,  155,
      155,  156,  156,  156,  157,   97,  157,  157,  157,  158,
      158,  158,   96,   95,  157,   93,   92,  158,  159,  159,
      159,   62,   61,  160,  160,   60,  159,  160,  160,  160,
      161,  161,  161,  162,   59,  162,  162,  162,  163,  163,
      163,   53,   52,  162,   51,   50,  163,  164,  164,  164,
       49,   47,  165,  165,    0,  164,  165,  165,  165,  166,
      166,  166,  167,    0,  167,  167,  167,  168,  168,  168,
        0,    0,  167,    0,    0,  168,  169,  169,  169,    0,

        0,  170,  170,    0,  169,  170,  170,  170,  178,  178,
      178,  179,  179,  179,  180,    0,  180,  180,  180,  181,
      181,  181,    0,    0,  180,    0,    0,  181,  182,  182,
      182,    0,    0,  183,  183,    0,  182,  183,  183,  183,
      184,  184,  184,  185,    0,  185,  185,  185,  186,  186,
      186,    0,    0,  185,    0,    0,  186,  187,  187,  187,
        0,    0,  188,  188,    0,  187,  188,  188,  188,  189,
      189,  189,  190,    0,  190,  190,  190,  191,  191,  191,
        0,    0,  190,    0,    0,  191,  192,  192,  192,    0,
        0,  193,  193,    0,  192,  193,  193,  193,  194,  194,

      194,  195,    0,  195,  195,  195,  196,  196,  196,    0,
        0,  195,    0,    0,  196,  197,  197,  197,    0,    0,
      198,  198,    0,  197,  198,  198,  198,  202,  202,    0,
        0,  202,  202,  202,  203,  203,  203,  204,  204,  204,
      211,  211,    0,    0,  211,  211,  211,  212,  212,  212,
      213,  213,  213,  214,  214,    0,    0,  214,  214,  214,
      215,  215,  215,  216,  216,  216,  217,  217,    0,    0,
      217,  217,  217,  218,  218,  218,  219,  219,  219,  220,
      220,    0,    0,  220,  220,  220,  221,  221,  221,  222,
      222,  222,  223,  223,    0,    0,  223,  223,  223,  224,

      224,  224,  225,  225,  225,  226,  226,    0,    0,  226,
      226,  226,  227,  227,  227,  228,  228,  228,  229,  229,
        0,    0,  229,  229,  229,  230,  230,  230,  231,  231,
      231,  232,  232,    0,    0,  232,  232,  232,  233,  233,
      233,  234,  234,  234,  235,  235,    0,    0,  235,  235,
      235,  236,  236,  236,  237,  237,  237,  243,  243,    0,
        0,  243,  243,  243,  244,  244,  244,  245,  245,  245,
      246,  246,    0,    0,  246,  246,  246,  247,  247,  247,
      248,  248,  248,  249,  249,    0,    0,  249,  249,  249,
      250,  250,  250,  251,  251,  251,  252,  252,    0,    0,

      252,  252,  252,  253,  253,  253,  254,  254,  254,  256,
      256,  256,  257,  257,  257,  266,  266,  266,  267,  267,
      267,  268,  268,  268,  269,  269,  269,  270,  270,  270,
      271,  271,  271,  272,  272,  272,  273,  273,  273,  274,
      274,  274,  275,  275,  275,  276,  276,  276,  277,  277,
      277,  278,  278,  278,  279,  279,  279,  280,  280,  280,
      281,  281,  281,  282,  282,  282,  283,  283,  283,  285,
      285,  285,  286,  286,  286,  287,  287,  287,  288,  288,
      288,  289,  289,  289,  290,  290,  290,  291,  291,  291,
      292,  292,  292,  381,  381,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "LexZemaxNonSeq.l"
#define INITIAL 0
#line 3 "LexZemaxNonSeq.l"
  // Übersetzt wird das ganze mit flex++ xml.lex und dann linken mit -lfl
  // flex++ xml.lex; g++ lex.yy.cc -lfl; ./a.out < beispiel.xml
  // flex++ ito.lex; g++ lex.yy.cc -lfl; . do.sh > test

  // Vorgehen:
  // 1. Das automatische Anlegen der Objekte für den Bereicht OBJECT hinkriegen
  // 2. Den ganzen Kram mehr oder weniger kopieren und für MeasurementEntity machen
  // 3. Den Kram in unsere Task Klasse einbauen / dazulinken / Makefile
  // 4. Dokumentation
  // 5. Die ganzen set/get Funktionen für Task machen, so dass bequemes Interface
  //    vorhanden ist.
  // 6. Definition der ganzen Variablen, die für uns relevant sind
  // 7. Output 
  // 8. Tests für Mikrolinsen und ein paar andere Objekte
  // Fehlerdetektion in den Input Files !

#include<stdio.h>
#include <iostream>
#include <stdlib.h>
#include "FlexZemax.h"

char yylval[20];

extern FILE *yyin;

extern FILE *yyout;

parseDOEResultStruct *doeResultStructPtr;
int doeCoeffIndex=0;
int doeIndex=0;
int lexDOENr=0;

parseGlassResultStruct *glassResultStructPtr;
short glassParamsIndex=0;
char search_glassName[PARSERR_LENGTH];

ParseGratingResultStruct *gratingResultStructPtr;
int gratingOrderIndex=0;
int gratingEffIndexOrder=0;
int gratingEffIndexLambda=0;
int gratingLambdaIndex=0;

// flag to signal error inside yylex()
bool LexerErr;
// flag to signal that glass name was found in glass catalog
bool glassFound;
bool doeErr;

double scale2m=0.001;
double scale2mm=1;
double scale2um=1000;

#define GLASS 1

#define GRATING 2

#define DOEDET 3

#define GRATINGDET 4

#define GRATINGDET_NRLAMBDA 5

#define GRATINGDET_LAMBDA 6

#define GRATINGDET_NRORDERS 7

#define GRATINGDET_ORDERS 8

#define GRATINGDET_RTP01Ptr 9

#define GRATINGDET_RTP10Ptr 10

#define GRATINGDET_RTS01Ptr 11

#define GRATINGDET_RTS10Ptr 12

#define GRATINGDET_G 13

#define GLASSDET 14

#define GLASSDET_NAME 15

#define GLASSDET_FORMULA 16

#define GLASSDET_RANGEMIN 17

#define GLASSDET_RANGEMAX 18

#define GLASSDET_NOM 19

#define GLASSDET_DENOM 20

#define GENERAL_LENS_DATA 21

#define GENERAL_LENS_DATA_UNITS 22

#line 856 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 105 "LexZemaxNonSeq.l"

		  
#line 1010 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 381 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1196 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 107 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "found beginning of glass library \n");
		  BEGIN	GLASS;
		  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "LexZemaxNonSeq.l"
{
		  BEGIN GRATINGDET;
		  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 116 "LexZemaxNonSeq.l"
{
		  doeCoeffIndex=0;
		  doeIndex=0;
		  fprintf( yyout, "found DOE file marker");
		  doeErr=false;
		  BEGIN DOEDET;
		 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 124 "LexZemaxNonSeq.l"
{
		fprintf( yyout, "surprised finding %s \n", yytext);
	 }
	YY_BREAK
/* -----------------------DOE Parser------------------------------*/
case 5:
YY_RULE_SETUP
#line 130 "LexZemaxNonSeq.l"
{
			fprintf( yyout, " %f;", atof(yytext));
			if (doeIndex==lexDOENr)
			{
				doeResultStructPtr->coeffArray[doeCoeffIndex]=atof(yytext);
				doeCoeffIndex++;
			}
			BEGIN DOEDET;
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 140 "LexZemaxNonSeq.l"
{
			doeIndex++;
			BEGIN DOEDET;
			} 
	YY_BREAK
/* -----------------------Grating Parser--------------------------*/
case 7:
YY_RULE_SETUP
#line 147 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "nr of wavelengths:");
		  BEGIN GRATINGDET_NRLAMBDA;
		  }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 152 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, " %i;", atoi(yytext));
		  gratingResultStructPtr->nrWavelengths=atoi(yytext);
		  BEGIN GRATINGDET;
		  }		  
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 158 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "nr of diff orders:");
		  BEGIN GRATINGDET_NRORDERS;
		  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 163 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, " %i;", atoi(yytext));
		  gratingResultStructPtr->nrOrders=atoi(yytext);
		  BEGIN GRATINGDET;
		  }		  
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 169 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "diff orders: ");
		  gratingOrderIndex=0;
		  gratingResultStructPtr->diffOrdersPtr=(short*) calloc(gratingResultStructPtr->nrOrders,sizeof(short));
		  BEGIN GRATINGDET_ORDERS;
		  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 176 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%i, ", atoi(yytext));
		gratingResultStructPtr->diffOrdersPtr[gratingOrderIndex]=atoi(yytext);
		gratingOrderIndex++;
		if (gratingOrderIndex>=gratingResultStructPtr->nrOrders)
		{	
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET;
		}
		else
			BEGIN GRATINGDET_ORDERS;
		}	
	YY_BREAK
/*-------------------------RTp01---------------------------------------*/
case 13:
YY_RULE_SETUP
#line 191 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "RTp01: ");
		  gratingEffIndexLambda=0;
		  gratingEffIndexOrder=0;
		  gratingResultStructPtr->RTP01Ptr=(double*) calloc(gratingResultStructPtr->nrOrders*gratingResultStructPtr->nrWavelengths,sizeof(double));
		  BEGIN GRATINGDET_RTP01Ptr;
		  }			
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 199 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f, ", atof(yytext));
		gratingResultStructPtr->RTP01Ptr[gratingEffIndexLambda+gratingResultStructPtr->nrWavelengths*gratingEffIndexOrder]=atof(yytext);
		gratingEffIndexLambda++;
		if (gratingEffIndexLambda>=gratingResultStructPtr->nrWavelengths)
		{	
			gratingEffIndexLambda=0;
			gratingEffIndexOrder++;
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET_RTP01Ptr;
		}
		if (gratingEffIndexOrder>=gratingResultStructPtr->nrOrders)
		{
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET;
		}		
		}	
	YY_BREAK
/*-------------------------RTp10---------------------------------------*/
case 15:
YY_RULE_SETUP
#line 219 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "RTp10: ");
		  gratingEffIndexLambda=0;
		  gratingEffIndexOrder=0;
		  gratingResultStructPtr->RTP10Ptr=(double*) calloc(gratingResultStructPtr->nrOrders*gratingResultStructPtr->nrWavelengths,sizeof(double));
		  BEGIN GRATINGDET_RTP10Ptr;
		  }			
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 227 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f, ", atof(yytext));
		gratingResultStructPtr->RTP10Ptr[gratingEffIndexLambda+gratingResultStructPtr->nrWavelengths*gratingEffIndexOrder]=atof(yytext);
		gratingEffIndexLambda++;
		if (gratingEffIndexLambda>=gratingResultStructPtr->nrWavelengths)
		{	
			gratingEffIndexLambda=0;
			gratingEffIndexOrder++;
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET_RTP10Ptr;
		}
		if (gratingEffIndexOrder>=gratingResultStructPtr->nrOrders)
		{
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET;
		}		
		}	
	YY_BREAK
/*-------------------------RTs01---------------------------------------*/
case 17:
YY_RULE_SETUP
#line 247 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "RTs01: ");
		  gratingEffIndexLambda=0;
		  gratingEffIndexOrder=0;
		  gratingResultStructPtr->RTS01Ptr=(double*) calloc(gratingResultStructPtr->nrOrders*gratingResultStructPtr->nrWavelengths,sizeof(double));
		  BEGIN GRATINGDET_RTS01Ptr;
		  }			
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 255 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f, ", atof(yytext));
		gratingResultStructPtr->RTS01Ptr[gratingEffIndexLambda+gratingResultStructPtr->nrWavelengths*gratingEffIndexOrder]=atof(yytext);
		gratingEffIndexLambda++;
		if (gratingEffIndexLambda>=gratingResultStructPtr->nrWavelengths)
		{	
			gratingEffIndexLambda=0;
			gratingEffIndexOrder++;
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET_RTS01Ptr;
		}
		if (gratingEffIndexOrder>=gratingResultStructPtr->nrOrders)
		{
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET;
		}		
		}	
	YY_BREAK
/*-------------------------RTs10---------------------------------------*/
case 19:
YY_RULE_SETUP
#line 275 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "RTs10: ");
		  gratingEffIndexLambda=0;
		  gratingEffIndexOrder=0;
		  gratingResultStructPtr->RTS10Ptr=(double*) calloc(gratingResultStructPtr->nrOrders*gratingResultStructPtr->nrWavelengths,sizeof(double));
		  BEGIN GRATINGDET_RTS10Ptr;
		  }			
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 283 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f, ", atof(yytext));
		gratingResultStructPtr->RTS10Ptr[gratingEffIndexLambda+gratingResultStructPtr->nrWavelengths*gratingEffIndexOrder]=atof(yytext);
		gratingEffIndexLambda++;
		if (gratingEffIndexLambda>=gratingResultStructPtr->nrWavelengths)
		{	
			gratingEffIndexLambda=0;
			gratingEffIndexOrder++;
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET_RTS10Ptr;
		}
		if (gratingEffIndexOrder>=gratingResultStructPtr->nrOrders)
		{
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET;
		}		
		}		
	YY_BREAK
/*-------------------------lambda---------------------------------------*/
case 21:
YY_RULE_SETUP
#line 303 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "lambda: ");
		  gratingLambdaIndex=0;
		  gratingResultStructPtr->lambdaPtr=(double*) calloc(gratingResultStructPtr->nrWavelengths,sizeof(double));
		  BEGIN GRATINGDET_LAMBDA;
		  }			
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 310 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f, ", atof(yytext));
		gratingResultStructPtr->lambdaPtr[gratingLambdaIndex]=atof(yytext)*1e-3;
		gratingLambdaIndex++;
		if (gratingLambdaIndex>=gratingResultStructPtr->nrWavelengths)
		{	
			fprintf(yyout, ";\n");
			BEGIN GRATINGDET;
		}
		else
			BEGIN GRATINGDET_LAMBDA;
		}				
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 323 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "error!!! number of wavelengths is less than specified");
		std::cout << "error in yylex(): number of wavelentghs is less than specified" << std::endl;
		LexerErr=true;
		BEGIN GRATINGDET;
		}
	YY_BREAK
/*-------------------------grating constant------------------------------------*/
case 24:
YY_RULE_SETUP
#line 333 "LexZemaxNonSeq.l"
{
		  fprintf( yyout, "g: ");
		  BEGIN GRATINGDET_G;
		  }			
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 338 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f, ", atof(yytext));
		gratingResultStructPtr->g=atof(yytext)*1e-3;
		BEGIN GRATINGDET;
		}			
	YY_BREAK
/*----------------------------------------------------------------*/				  
/* -----------------------Glass Parser----------------------------*/
/*----------------------------------------------------------------*/
case 26:
YY_RULE_SETUP
#line 348 "LexZemaxNonSeq.l"
{
		fprintf( yyout, "found beginning of glass definition");
		BEGIN GLASSDET_NAME;
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 353 "LexZemaxNonSeq.l"
{
		fprintf( yyout, "name: %s", yytext );
		// if we found the glass we were looking for
		if (!strcmp(yytext, search_glassName))
		{
			fprintf( yyout, "name: %s", yytext);
			//sprintf( glassResultStructPtr->glassName, yytext);
			glassFound=true;
			BEGIN GLASSDET_FORMULA;
		}
		else
			BEGIN GLASS;
		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 367 "LexZemaxNonSeq.l"
{
		fprintf( yyout, "formula: %i;", atoi(yytext));		
		glassResultStructPtr->dispersionFormulaIndex=atoi(yytext);
		BEGIN GLASSDET;
		}
	YY_BREAK
/* ------------------------ wavelength range -------------------------*/
case 29:
YY_RULE_SETUP
#line 375 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "wavelength range: ");
		BEGIN GLASSDET_RANGEMIN;
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 380 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f, ", atof(yytext)*scale2um);
		glassResultStructPtr->lambdaMin=atof(yytext);
		BEGIN GLASSDET_RANGEMAX;
		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 386 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f \n", atof(yytext));
		glassResultStructPtr->lambdaMax=atof(yytext);
		BEGIN GLASS;
		}
	YY_BREAK
/* ------------------------- nominator of dispersion formula ----------*/
case 32:
YY_RULE_SETUP
#line 394 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "nominator: ");
		glassParamsIndex=0;
		BEGIN GLASSDET_NOM;
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 400 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f ", atof(yytext));
		glassResultStructPtr->paramsNom[glassParamsIndex]=atof(yytext);
		glassParamsIndex++;
		if (glassParamsIndex>5)
			BEGIN GLASSDET;
		else
			BEGIN GLASSDET_NOM;
		}		
	YY_BREAK
/* ------------------------- denominator of dispersion formula ----------*/
case 34:
YY_RULE_SETUP
#line 412 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "denominator: ");
		glassParamsIndex=0;
		BEGIN GLASSDET_DENOM;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 418 "LexZemaxNonSeq.l"
{
		fprintf(yyout, "%f ", atof(yytext));
		glassResultStructPtr->paramsDenom[glassParamsIndex]=atof(yytext);
		glassParamsIndex++;
		if (glassParamsIndex>5)
			BEGIN GLASSDET;
		else
			BEGIN GLASSDET_DENOM;
		}				
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 428 "LexZemaxNonSeq.l"
{}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 430 "LexZemaxNonSeq.l"
ECHO;
	YY_BREAK
#line 1516 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(GLASS):
case YY_STATE_EOF(GRATING):
case YY_STATE_EOF(DOEDET):
case YY_STATE_EOF(GRATINGDET):
case YY_STATE_EOF(GRATINGDET_NRLAMBDA):
case YY_STATE_EOF(GRATINGDET_LAMBDA):
case YY_STATE_EOF(GRATINGDET_NRORDERS):
case YY_STATE_EOF(GRATINGDET_ORDERS):
case YY_STATE_EOF(GRATINGDET_RTP01Ptr):
case YY_STATE_EOF(GRATINGDET_RTP10Ptr):
case YY_STATE_EOF(GRATINGDET_RTS01Ptr):
case YY_STATE_EOF(GRATINGDET_RTS10Ptr):
case YY_STATE_EOF(GRATINGDET_G):
case YY_STATE_EOF(GLASSDET):
case YY_STATE_EOF(GLASSDET_NAME):
case YY_STATE_EOF(GLASSDET_FORMULA):
case YY_STATE_EOF(GLASSDET_RANGEMIN):
case YY_STATE_EOF(GLASSDET_RANGEMAX):
case YY_STATE_EOF(GLASSDET_NOM):
case YY_STATE_EOF(GLASSDET_DENOM):
case YY_STATE_EOF(GENERAL_LENS_DATA):
case YY_STATE_EOF(GENERAL_LENS_DATA_UNITS):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 381 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 381 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 380);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 430 "LexZemaxNonSeq.l"


// ____________________________________________________________

//int main()
//    {
//		yyout = fopen( "e:\\mauch\\prescriptionLexOut.txt", "w" ) ;
//		yyin = fopen( "e:\\mauch\\prescription.txt", "r" ) ;
    
//		while(yylex() != 0)
//			;
//		fclose(yyout);
//    }

parserError parseDOEFile(parseDOEResultStruct** parseResultsDOEPtrPtr, FILE *hfile, int DOEnr)
{
	char filepath[512];
	sprintf(filepath, "%s" PATH_SEPARATOR "%s", OUTPUT_FILEPATH, "DOELexOut.txt");
	yyout = fopen( filepath, "w" ) ;
	lexDOENr=DOEnr;
	fprintf( yyout, "starting to parse DOE file \n");
	doeResultStructPtr=new parseDOEResultStruct();
	doeErr=true;
	yyin = hfile;
    /* do the actual parsing */
//	while(yylex() != 0)
//		;
	yylex();
	fclose(yyout);
	if (doeErr)
	{
		std::cout << "error in parseDOEFile" << std::endl;
		return PARSER_ERR;
	}
	doeResultStructPtr->coeffLength=doeCoeffIndex;
	sprintf(doeResultStructPtr->errMsg, "no error");
	*parseResultsDOEPtrPtr=doeResultStructPtr;
	return PARSER_NO_ERR;
}	

parserError parseMicroSimGratingData(ParseGratingResultStruct** parseResultsGratingPtrPtr, FILE *hfile)
{
	char filepath[512];
	sprintf(filepath, "%s" PATH_SEPARATOR "%s", OUTPUT_FILEPATH, "gratingLexOut.txt");
	yyout = fopen( filepath, "w" ) ;
	gratingResultStructPtr=new ParseGratingResultStruct();
	yyin = hfile;
    /* do the actual parsing */
	while(yylex() != 0)
		;
	fclose(yyout);

	sprintf(gratingResultStructPtr->errMsg, "no error");
	*parseResultsGratingPtrPtr=gratingResultStructPtr;
	return PARSER_NO_ERR;
}

parserError parseZemaxGlassCatalogOld(parseGlassResultStruct** parseResultsGlassPtrPtr, FILE *hfile, char *glassName)
{
	char filepath[512];
	sprintf(filepath, "%s" PATH_SEPARATOR "%s", OUTPUT_FILEPATH, "glassLexOut.txt");
	yyout = fopen( filepath, "w" ) ;
	fprintf( yyout, "starting to parse glass catalog \n");
	glassResultStructPtr=new parseGlassResultStruct();
	sprintf(search_glassName, "%s", glassName);
	yyin = hfile;
	//yyin = fopen( "e:\\mauch\\glass.AGF", "r" );
    /* do the actual parsing */
//	while(yylex() != 0)
//		;
	yylex();
	fclose(yyout);
	if (!glassFound)
	{
		std::cout << "error in parseZemaxGlassCatalog: glass name -%s was not found" << (*glassName) << std::endl;
		return PARSER_ERR;
	}
	
	sprintf(glassResultStructPtr->errMsg, "no error");
	*parseResultsGlassPtrPtr=glassResultStructPtr;
	return PARSER_NO_ERR;
}	

parserError parseZemaxGlassCatalog(parseGlassResultStruct** parseResultsGlassPtrPtr, FILE *hfile, const char *glassName)
{
	char filepath[512];
	sprintf(filepath, "%s" PATH_SEPARATOR "%s", OUTPUT_FILEPATH, "glassLexOut.txt");
	yyout = fopen( filepath, "w" ) ;
	fprintf( yyout, "starting to parse glass catalog \n");
	glassResultStructPtr=new parseGlassResultStruct();
	sprintf(search_glassName, "%s", glassName);
	yyin = hfile;
	glassFound=false;
	//yyin = fopen( "e:\\mauch\\glass.AGF", "r" );
    /* do the actual parsing */
//	while(yylex() != 0)
//		;
	yylex();
	fclose(yyout);
	if (!glassFound)
	{
		std::cout << "error in parseZemaxGlassCatalog: glass name -%s was not found" << (*glassName) << std::endl;
		return PARSER_ERR;
	}
	
	sprintf(glassResultStructPtr->errMsg, "no error");
	*parseResultsGlassPtrPtr=glassResultStructPtr;
	return PARSER_NO_ERR;
}	

